name: Deploy to GitHub Pages

on:
  push:
    paths:
      - "index.html"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Deploy to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: "."

    - name: Publish Pages
      uses: actions/deploy-pages@v3
